server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/DarthDS4711/MicroServicios
          search-paths: config-data
  application:
    name: ConfigServer